# This is a basic workflow to help you get started with Actions

name: BBB

# Controls when the workflow will run
on:
  workflow_dispatch:
permissions: write-all
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jambon:
    env:
      BRANCH_NAME: main
    runs-on: ubuntu-latest
    steps:
      - name: Poke the bear
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6
        continue-on-error: true
        env:
          DISPLAY_TITLE: ${{ github.event.workflow_run.display_title }}
          PR_BODY: '#${{ github.event.workflow_run.pull_requests[0].number }}'
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'AAA',
              ref: process.env.BRANCH_NAME,
            });
      - name: Poke the bear
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6
        continue-on-error: true
        env:
          DISPLAY_TITLE: ${{ github.event.workflow_run.display_title }}
          PR_BODY: '#${{ github.event.workflow_run.pull_requests[0].number }}'
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'salsifi',
              ref: process.env.BRANCH_NAME,
            });
      - name: Poke the bear
        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6
        continue-on-error: true
        env:
          DISPLAY_TITLE: ${{ github.event.workflow_run.display_title }}
          PR_BODY: '#${{ github.event.workflow_run.pull_requests[0].number }}'
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'salsifi.yml',
              ref: process.env.BRANCH_NAME,
            });
